name: debug_overlay_example
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  supernova_flutter:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_flutter
      ref: d863bb61d8a89cb2e23c6ac6f3510c80061d10b7

dependency_overrides:
  debug_overlay:
    path: ../

flutter:
  uses-material-design: true
