name: debug_overlay_example
publish_to: none

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.0'

dependencies:
  debug_overlay:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  supernova_lints:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_lints
      ref: 88ffdb5c434ea2d1012c0f98f478b9240c2aedbf

flutter:
  uses-material-design: true
