name: debug_overlay_example
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  debug_overlay:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
