name: Build & Lint

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

env:
  JAVA_VERSION: 12.x
  FLUTTER_CHANNEL: beta

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - run: flutter pub get

      - name: Run linter
        run: flutter analyze > flutter_analyze_report.txt
        continue-on-error: true

      - uses: actions/setup-ruby@v1
        if: github.event_name == 'pull_request'
        with:
          ruby-version: '2.6'
      - name: Install ruby gems
        run: |
          gem install bundler
          bundle install --without documentation
        if: github.event_name == 'pull_request'
      - name: Run danger on generated report
        uses: MeilCli/danger-action@v5.4.10
        if: github.event_name == 'pull_request'
        with:
          danger_file: Dangerfile
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.BOT_TOKEN }}

  build-example:
    name: Build example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - run: flutter pub get
        working-directory: example

      - run: flutter build apk
        working-directory: example

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: example-apk
          path: example/build/app/outputs/apk/release/app-release.apk
